sudo: required

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - sudo apt update
  - sudo apt -y install python3-pyqt5 python3-pip
  - pip3 install configparser

script: python3 Daikin.py
