os: linux
language: python
sudo: true

python:
#  - "3.4"
#  - "3.5"
#  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev libxkbcommon-x11-0 libegl1-mesa-dev 
  - sudo apt-get -y install python3-pyqt5 python3-pip

install:
  - sudo apt update
  - pip3 install configparser pytest codecov
  - pip3 install --upgrade --force-reinstall pyqt5

services:
  - xvfb

script: pytest Daikin.py

after_success:
  - codecov
