sudo: required

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - sudo apt update
  - sudo apt -y install python3-pyqt5 python3-pip libegl1-mesa
  - pip3 install configparser
  - pip3 install --upgrade --force-reinstall pyqt5


script: python3 Daikin.py
